### ISSUE TITLE
Visualization of signals files

### ISSUE THREAD

**Issue by breznak** [OpenElectronicsLab/OpenHardwareExG#1]
Hi, 
I'm one of the developers of https://github.com/nupic-community/nupic.visualizations , a tool for visualization of time-series data, eg ECG, ... 
I'm wondering if it would be of interest for your project?

**Comment by ericherman** [comment]
Hello breznak,

At the moment we are focusing on the next generation hardware, but when we next get back to visualization, we may indeed find that nupic.visualizations is nicer than what we have already been using[1].

Thanks for the pointer,
 -Eric

[1] https://github.com/OpenElectronicsLab/GDAQRec
